### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by muxinxy** [AngelCloudflare/Lucky-Stun-Proxy#1]
内网穿透群晖，控制台报错：

> Refused to display 'http://123.123.123.123:12345/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

修改群晖设置后，可以正常打开登录页面，但是登录时提示`您没有权限使用本项服务`

![image](https://github.com/AngelCloudflare/Lucky-Stun-Proxy/assets/32673109/61c16994-9a81-48f8-962f-8358d684daa0)

![image](https://github.com/AngelCloudflare/Lucky-Stun-Proxy/assets/32673109/01777112-7fa6-4f38-a558-6121264b4975)

**Comment by AngelCloudflare** [comment]
貌似群晖有这毛病，搜了下，你可以看看。
点此查看：https://kb.synology.cn/zh-cn/DSM/tutorial/you_are_not_authorized_to_use_service_all_users
如果外部使用SSL的话，本地项目也应该修改相对资源路径

**Comment by muxinxy** [comment]
> 貌似群晖有这毛病，搜了下，你可以看看。 点此查看：https://kb.synology.cn/zh-cn/DSM/tutorial/you_are_not_authorized_to_use_service_all_users 如果外部使用SSL的话，本地项目也应该修改相对资源路径

改成使用CF页面规则跳转了
